In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('upstart-loan-data.csv')

In [4]:
df

,Unnamed: 0,Loan ID,Loan Grade,Term (months),Origination Date,Interest Rate,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status,Charged Off Amount,Charged Off Date
0,15758,L17471,C,36,2015-11-04,12.56,16.94,492.00,8200.0,4733.79,89,Delinquent,NaN,NaN
1,46818,L49499,B,60,2016-12-19,15.98,18.64,1400.00,25000.0,22987.76,0,Current,NaN,NaN
2,7461,L28976,C,60,2016-03-23,18.02,20.44,325.00,6500.0,5296.60,0,Current,NaN,NaN
3,191,L286,C,36,2014-06-10,14.15,17.80,250.00,5000.0,0.00,0,Matured,NaN,NaN
4,46967,L53569,B,36,2017-02-01,10.02,13.43,239.10,5000.0,4388.82,0,Current,NaN,NaN
5,60545,L65433,D,36,2017-05-08,13.72,18.14,210.00,3500.0,3341.06,0,Current,NaN,NaN
6,10993,L9304,B,36,2015-07-06,9.09,12.62,150.00,3000.0,0.00,0,Matured,NaN,NaN
7,18172,L17264,C,36,2015-11-02,13.30,17.70,840.00,14000.0,6898.95,0,Current,NaN,NaN
8,44014,L45997,B,36,2016-11-10,11.73,15.78,672.00,12000.0,9678.61,0,Current,NaN,NaN
9,60950,L65707,A,36,2017-05-09,8.75,12.74,560.00,10000.0,9510.69,0,Current,NaN,NaN
10,36210,L36279,A,36,2016-07-20,8.13,12.09,280.00,5000.0,3466.24,0,Current,NaN,NaN
11,31223,L30232,B,36,2016-04-06,9.78,12.60,120.00,3000.0,1835.77,0,Current,NaN,NaN
12,57762,L61704,E,60,2017-04-17,24.08,27.21,450.00,7500.0,7368.22,15,In Grace,NaN,NaN
13,58325,L64299,E,60,2017-05-02,26.56,29.79,804.00,13400.0,13296.61,0,Current,NaN,NaN
14,66776,L72855,B,60,2017-06-23,11.65,14.21,168.00,3000.0,2712.37,0,Current,NaN,NaN
15,65107,L71484,C,60,2017-06-07,14.37,17.21,900.00,15000.0,14766.56,0,Current,NaN,NaN
16,4838,L5135,A,36,2015-03-18,6.89,10.38,500.00,10000.0,1485.01,0,Current,NaN,NaN
17,9923,L27944,A,36,2016-03-09,6.39,9.15,160.00,4000.0,2310.00,0,Current,NaN,NaN
18,5977,L11120,D,36,2015-08-10,24.87,29.58,540.00,9000.0,2931.28,0,Current,NaN,NaN
19,40295,L40975,B,36,2016-09-19,8.68,12.65,392.00,7000.0,0.00,0,Matured,NaN,NaN
20,9495,L9011,A,36,2015-06-29,8.09,11.61,1250.00,25000.0,0.00,0,Matured,NaN,NaN
21,3509,L64755,E,60,2017-05-08,27.97,29.79,124.76,3700.0,3642.04,0,Current,NaN,NaN
22,29993,L28796,C,36,2016-03-22,14.85,15.74,67.50,5400.0,3291.18,0,Current,NaN,NaN
23,31560,L30713,AA,36,2016-04-13,4.99,6.34,30.00,1500.0,901.98,0,Current,NaN,NaN
24,53744,L58928,B,36,2017-03-27,10.40,14.43,728.00,13000.0,11719.18,0,Current,NaN,NaN
25,45291,L47038,A,60,2016-11-22,9.57,12.07,672.00,12000.0,10706.11,0,Current,NaN,NaN
26,3956,L4059,A,36,2015-02-11,7.95,11.46,750.00,15000.0,3196.81,0,Current,NaN,NaN
27,31291,L50257,B,60,2016-12-27,13.06,14.48,314.70,10000.0,7718.66,0,Current,NaN,NaN
28,74863,L83931,A,36,2017-07-24,8.10,12.33,238.20,4000.0,4000.00,0,Current,NaN,NaN
29,48402,L51135,A,60,2017-01-09,10.82,13.35,996.80,17800.0,16411.63,0,Current,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,72640,L83742,E,60,2017-07-24,25.88,29.81,335.43,4600.0,4600.00,0,Current,NaN,NaN
9971,32648,L32484,B,36,2016-05-20,10.88,13.73,140.00,3500.0,2053.31,0,Current,NaN,NaN
9972,37473,L39904,A,36,2016-09-06,6.95,10.88,560.00,10000.0,7424.87,0,Current,NaN,NaN
9973,4052,L3318,B,36,2015-01-12,11.35,14.94,550.00,11000.0,1630.62,0,Current,NaN,NaN
9974,34890,L34942,B,60,2016-06-29,11.60,14.16,952.00,17000.0,14346.15,0,Current,NaN,NaN
9975,75588,L85865,C,36,2017-07-31,12.06,16.84,177.04,2700.0,2700.00,0,Current,NaN,NaN
9976,49911,L52430,E,36,2017-01-23,24.52,29.23,60.00,1000.0,878.49,0,Current,NaN,NaN
9977,44373,L55711,B,60,2017-02-23,12.93,15.52,840.00,15000.0,14073.28,0,Current,NaN,NaN
9978,43397,L44993,B,60,2016-10-31,13.84,16.44,112.00,2000.0,1671.70,31,Delinquent,NaN,NaN
9979,15958,L13264,D,36,2015-09-14,17.78,22.29,510.00,8500.0,4494.41,79,Delinquent,NaN,NaN
9980,66767,L74430,B,36,2017-06-19,9.52,13.38,379.33,7000.0,6754.77,0,Current,NaN,NaN
9981,25116,L28594,B,60,2016-03-21,12.64,14.09,320.00,10000.0,7906.15,0,Current,NaN,NaN
9982,51308,L53975,E,36,2017-02-06,25.03,29.77,114.00,1900.0,1709.71,0,Current,NaN,NaN
9983,4677,L82345,D,60,2017-07-18,16.22,19.47,627.01,9300.0,9300.00,0,Current,NaN,NaN
9984,36704,L36846,E,36,2016-07-26,25.24,29.96,1212.00,20200.0,0.00,187,Charged Off,20051.20,2017-05-27
9985,31032,L30335,A,36,2016-04-08,8.31,11.11,220.00,5500.0,3362.34,0,Current,NaN,NaN
9986,24070,L23607,A,36,2016-01-15,8.16,11.68,550.00,11000.0,0.00,0,Matured,NaN,NaN
9987,42947,L44277,A,36,2016-10-24,7.00,10.93,476.00,8500.0,5731.12,0,Current,NaN,NaN
9988,74979,L85686,C,36,2017-07-28,12.33,16.23,402.83,7500.0,7500.00,0,Current,NaN,NaN
9989,7777,L15433,C,36,2015-10-09,11.69,16.03,360.00,6000.0,2741.13,0,Current,NaN,NaN
9990,50157,L53605,B,36,2017-02-02,9.06,13.02,1232.00,22000.0,19299.64,0,Current,NaN,NaN
9991,21923,L21010,B,36,2015-12-10,9.03,12.57,800.00,16000.0,0.00,0,Matured,NaN,NaN
9992,10713,L9005,D,36,2015-06-29,14.83,19.26,180.00,3000.0,0.00,0,Charged Off,2031.29,2017-03-02
9993,66275,L72611,B,60,2017-06-13,12.18,14.75,476.00,8500.0,8395.22,0,Current,NaN,NaN
9994,45675,L47575,C,36,2016-11-29,12.75,17.10,1014.00,16900.0,14104.14,0,Current,NaN,NaN
9995,22698,L27763,A,36,2016-03-07,7.92,9.88,436.13,15400.0,8980.34,0,Current,NaN,NaN
9996,6891,L5683,B,36,2015-04-06,10.93,14.51,800.00,16000.0,0.00,0,Matured,NaN,NaN
9997,61625,L67159,B,36,2017-05-16,9.07,12.80,1363.18,26000.0,24733.78,0,Current,NaN,NaN
9998,15024,L12888,A,36,2015-09-10,7.23,10.72,320.00,6400.0,0.00,0,Matured,NaN,NaN
9999,29531,L30309,E,36,2016-04-11,26.01,29.93,1685.00,33700.0,24462.63,51,Delinquent,NaN,NaN

### Question 1

Drop all columns except for these... <b>['Loan Grade', 'Term (months)', 'Interest Rate', 'APR', 'Origination Fee', 'Loan Size', 'Outstanding Principal', 'Days Late', 'Delinquency Status']</b>

In [5]:
df.drop(df.columns.difference(['Loan Grade', 'Term (months)', 'Interest Rate', 'APR', 'Origination Fee', 'Loan Size', 'Outstanding Principal', 'Days Late', 'Delinquency Status']), 1, inplace=True)

In [6]:
df

,Loan Grade,Term (months),Interest Rate,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status
0,C,36,12.56,16.94,492.00,8200.0,4733.79,89,Delinquent
1,B,60,15.98,18.64,1400.00,25000.0,22987.76,0,Current
2,C,60,18.02,20.44,325.00,6500.0,5296.60,0,Current
3,C,36,14.15,17.80,250.00,5000.0,0.00,0,Matured
4,B,36,10.02,13.43,239.10,5000.0,4388.82,0,Current
5,D,36,13.72,18.14,210.00,3500.0,3341.06,0,Current
6,B,36,9.09,12.62,150.00,3000.0,0.00,0,Matured
7,C,36,13.30,17.70,840.00,14000.0,6898.95,0,Current
8,B,36,11.73,15.78,672.00,12000.0,9678.61,0,Current
9,A,36,8.75,12.74,560.00,10000.0,9510.69,0,Current
10,A,36,8.13,12.09,280.00,5000.0,3466.24,0,Current
11,B,36,9.78,12.60,120.00,3000.0,1835.77,0,Current
12,E,60,24.08,27.21,450.00,7500.0,7368.22,15,In Grace
13,E,60,26.56,29.79,804.00,13400.0,13296.61,0,Current
14,B,60,11.65,14.21,168.00,3000.0,2712.37,0,Current
15,C,60,14.37,17.21,900.00,15000.0,14766.56,0,Current
16,A,36,6.89,10.38,500.00,10000.0,1485.01,0,Current
17,A,36,6.39,9.15,160.00,4000.0,2310.00,0,Current
18,D,36,24.87,29.58,540.00,9000.0,2931.28,0,Current
19,B,36,8.68,12.65,392.00,7000.0,0.00,0,Matured
20,A,36,8.09,11.61,1250.00,25000.0,0.00,0,Matured
21,E,60,27.97,29.79,124.76,3700.0,3642.04,0,Current
22,C,36,14.85,15.74,67.50,5400.0,3291.18,0,Current
23,AA,36,4.99,6.34,30.00,1500.0,901.98,0,Current
24,B,36,10.40,14.43,728.00,13000.0,11719.18,0,Current
25,A,60,9.57,12.07,672.00,12000.0,10706.11,0,Current
26,A,36,7.95,11.46,750.00,15000.0,3196.81,0,Current
27,B,60,13.06,14.48,314.70,10000.0,7718.66,0,Current
28,A,36,8.10,12.33,238.20,4000.0,4000.00,0,Current
29,A,60,10.82,13.35,996.80,17800.0,16411.63,0,Current
...,...,...,...,...,...,...,...,...,...
9970,E,60,25.88,29.81,335.43,4600.0,4600.00,0,Current
9971,B,36,10.88,13.73,140.00,3500.0,2053.31,0,Current
9972,A,36,6.95,10.88,560.00,10000.0,7424.87,0,Current
9973,B,36,11.35,14.94,550.00,11000.0,1630.62,0,Current
9974,B,60,11.60,14.16,952.00,17000.0,14346.15,0,Current
9975,C,36,12.06,16.84,177.04,2700.0,2700.00,0,Current
9976,E,36,24.52,29.23,60.00,1000.0,878.49,0,Current
9977,B,60,12.93,15.52,840.00,15000.0,14073.28,0,Current
9978,B,60,13.84,16.44,112.00,2000.0,1671.70,31,Delinquent
9979,D,36,17.78,22.29,510.00,8500.0,4494.41,79,Delinquent
9980,B,36,9.52,13.38,379.33,7000.0,6754.77,0,Current
9981,B,60,12.64,14.09,320.00,10000.0,7906.15,0,Current
9982,E,36,25.03,29.77,114.00,1900.0,1709.71,0,Current
9983,D,60,16.22,19.47,627.01,9300.0,9300.00,0,Current
9984,E,36,25.24,29.96,1212.00,20200.0,0.00,187,Charged Off
9985,A,36,8.31,11.11,220.00,5500.0,3362.34,0,Current
9986,A,36,8.16,11.68,550.00,11000.0,0.00,0,Matured
9987,A,36,7.00,10.93,476.00,8500.0,5731.12,0,Current
9988,C,36,12.33,16.23,402.83,7500.0,7500.00,0,Current
9989,C,36,11.69,16.03,360.00,6000.0,2741.13,0,Current
9990,B,36,9.06,13.02,1232.00,22000.0,19299.64,0,Current
9991,B,36,9.03,12.57,800.00,16000.0,0.00,0,Matured
9992,D,36,14.83,19.26,180.00,3000.0,0.00,0,Charged Off
9993,B,60,12.18,14.75,476.00,8500.0,8395.22,0,Current
9994,C,36,12.75,17.10,1014.00,16900.0,14104.14,0,Current
9995,A,36,7.92,9.88,436.13,15400.0,8980.34,0,Current
9996,B,36,10.93,14.51,800.00,16000.0,0.00,0,Matured
9997,B,36,9.07,12.80,1363.18,26000.0,24733.78,0,Current
9998,A,36,7.23,10.72,320.00,6400.0,0.00,0,Matured
9999,E,36,26.01,29.93,1685.00,33700.0,24462.63,51,Delinquent

In [56]:
df.Term.unique()

array([36, 60], dtype=int64)

### Interest Rates vs. APR

You may have or you will come across terms like interest rates and APR when you go out to get loans for homes, auto and in this instance (personal loans from Upstart, a lending company), as a borrower trying to get unsecured credit. The difference between interest rate and APR in the context of refinancing or taking out a mortgage (for a home) is...

- Interest rate refers to the annual cost of a loan to a borrower and is expressed as a percentage.
- APR is the annual cost of a loan to a borrower — including fees. Like an interest rate, the APR is expressed as a percentage. Unlike an interest rate however, it includes other charges or fees such as mortgage insurance, most closing costs, discount points and loan origination fees.

But what's the difference between unsecured and secured loan? If you borrow money to buy a home, say from a bank and if you were to skip paying on that loan, guess what the bank does? It takes away your home. So the bank is making a loan based on the fact that in worst-case scenarios, they have an asset (home) they can go after. That's secured credit and hence generally carry a lower interest rate.

Unsecured credit would be like a bank lending money to you on your credit card. If you don't pay, they will cancel your credit and destroy your credit score but that is it. They can't technically come after your other assets. That's a form of unsecured credit.

### Question 2

Now that you know the difference, drop the <b>Interest Rate</b> column as well and rename the column <b>Term (months)</b> to <b>Term</b>. Also check if all attributes are in the correct format (integers, float etc). If not, change them into the right format.

In [ ]:
df.drop(['Interest Rate'], axis = 1, inplace = True)

In [13]:
df.rename(columns = {'Term (months)':'Term'}, inplace = True)

In [14]:
df

,Loan Grade,Term,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status
0,C,36,16.94,492.00,8200.0,4733.79,89,Delinquent
1,B,60,18.64,1400.00,25000.0,22987.76,0,Current
2,C,60,20.44,325.00,6500.0,5296.60,0,Current
3,C,36,17.80,250.00,5000.0,0.00,0,Matured
4,B,36,13.43,239.10,5000.0,4388.82,0,Current
5,D,36,18.14,210.00,3500.0,3341.06,0,Current
6,B,36,12.62,150.00,3000.0,0.00,0,Matured
7,C,36,17.70,840.00,14000.0,6898.95,0,Current
8,B,36,15.78,672.00,12000.0,9678.61,0,Current
9,A,36,12.74,560.00,10000.0,9510.69,0,Current
10,A,36,12.09,280.00,5000.0,3466.24,0,Current
11,B,36,12.60,120.00,3000.0,1835.77,0,Current
12,E,60,27.21,450.00,7500.0,7368.22,15,In Grace
13,E,60,29.79,804.00,13400.0,13296.61,0,Current
14,B,60,14.21,168.00,3000.0,2712.37,0,Current
15,C,60,17.21,900.00,15000.0,14766.56,0,Current
16,A,36,10.38,500.00,10000.0,1485.01,0,Current
17,A,36,9.15,160.00,4000.0,2310.00,0,Current
18,D,36,29.58,540.00,9000.0,2931.28,0,Current
19,B,36,12.65,392.00,7000.0,0.00,0,Matured
20,A,36,11.61,1250.00,25000.0,0.00,0,Matured
21,E,60,29.79,124.76,3700.0,3642.04,0,Current
22,C,36,15.74,67.50,5400.0,3291.18,0,Current
23,AA,36,6.34,30.00,1500.0,901.98,0,Current
24,B,36,14.43,728.00,13000.0,11719.18,0,Current
25,A,60,12.07,672.00,12000.0,10706.11,0,Current
26,A,36,11.46,750.00,15000.0,3196.81,0,Current
27,B,60,14.48,314.70,10000.0,7718.66,0,Current
28,A,36,12.33,238.20,4000.0,4000.00,0,Current
29,A,60,13.35,996.80,17800.0,16411.63,0,Current
...,...,...,...,...,...,...,...,...
9970,E,60,29.81,335.43,4600.0,4600.00,0,Current
9971,B,36,13.73,140.00,3500.0,2053.31,0,Current
9972,A,36,10.88,560.00,10000.0,7424.87,0,Current
9973,B,36,14.94,550.00,11000.0,1630.62,0,Current
9974,B,60,14.16,952.00,17000.0,14346.15,0,Current
9975,C,36,16.84,177.04,2700.0,2700.00,0,Current
9976,E,36,29.23,60.00,1000.0,878.49,0,Current
9977,B,60,15.52,840.00,15000.0,14073.28,0,Current
9978,B,60,16.44,112.00,2000.0,1671.70,31,Delinquent
9979,D,36,22.29,510.00,8500.0,4494.41,79,Delinquent
9980,B,36,13.38,379.33,7000.0,6754.77,0,Current
9981,B,60,14.09,320.00,10000.0,7906.15,0,Current
9982,E,36,29.77,114.00,1900.0,1709.71,0,Current
9983,D,60,19.47,627.01,9300.0,9300.00,0,Current
9984,E,36,29.96,1212.00,20200.0,0.00,187,Charged Off
9985,A,36,11.11,220.00,5500.0,3362.34,0,Current
9986,A,36,11.68,550.00,11000.0,0.00,0,Matured
9987,A,36,10.93,476.00,8500.0,5731.12,0,Current
9988,C,36,16.23,402.83,7500.0,7500.00,0,Current
9989,C,36,16.03,360.00,6000.0,2741.13,0,Current
9990,B,36,13.02,1232.00,22000.0,19299.64,0,Current
9991,B,36,12.57,800.00,16000.0,0.00,0,Matured
9992,D,36,19.26,180.00,3000.0,0.00,0,Charged Off
9993,B,60,14.75,476.00,8500.0,8395.22,0,Current
9994,C,36,17.10,1014.00,16900.0,14104.14,0,Current
9995,A,36,9.88,436.13,15400.0,8980.34,0,Current
9996,B,36,14.51,800.00,16000.0,0.00,0,Matured
9997,B,36,12.80,1363.18,26000.0,24733.78,0,Current
9998,A,36,10.72,320.00,6400.0,0.00,0,Matured
9999,E,36,29.93,1685.00,33700.0,24462.63,51,Delinquent

In [15]:
df.dtypes

Loan Grade                object
Term                       int64
APR                      float64
Origination Fee          float64
Loan Size                float64
Outstanding Principal    float64
Days Late                  int64
Delinquency Status        object
dtype: object

### Question 3

Describe in a few words what type of variables are <b>Loan Grade</b>, <b>Term</b>, <b>Days Late</b> and <b>Delinquency Status</b> and why.

<b>Loan Grade</b>: Ordinal because Loan Grades serve as a rank.
<br>
<b>Term</b>:Discrete because number of Term months can only be whole numbers.
<br>
<b>Days Late</b>:Discrete because number of Days Late can only be whole numbers.
<br>
<b>Delinquency Status</b>: Nominal because Delinquency Status involves unordered categories.

### Question 4

Compute the average by <b>Loan Grade</b> for all columns and give a few remarks on what you observe for the <b>APR</b> and <b>Days Late</b> columns.

In [17]:
df.groupby(by = 'Loan Grade').mean()

,Term,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late
Loan Grade,,,,,,
A,40.481858,11.226493,608.045951,12282.244799,6428.668974,6.161587
AA,45.478060,8.464965,398.056490,13238.337182,6899.800139,2.766744
AAA,48.000000,6.518333,123.333333,12333.333333,9117.633333,0.000000
B,43.276596,14.380888,634.248265,12351.097074,7739.511007,10.098404
C,39.492491,17.312299,637.277255,11287.053340,7159.271932,15.167271
D,41.292308,21.407568,713.364571,12425.421245,6545.772066,39.327473
E,48.665546,27.348857,589.105403,9962.857143,7470.002361,18.111765

Observation: The higher the <b>Loan Grade</b>, the lower the <b>APR</b> and lower amount of <b>Days Late</b>.

### Question 5

Verify if there are any missing values in the dataset. Confirm that by applying the <b>size()</b> aggregation method on any of the columns.

In [23]:
df.groupby(by = 'Loan Grade')['Term','APR', 'Origination Fee', 'Loan Size', 'Outstanding Principal', 'Days Late', 'Delinquency Status'].count()

,Term,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status
Loan Grade,,,,,,,
A,2067,2067,2067,2067,2067,2067,2067
AA,433,433,433,433,433,433,433
AAA,6,6,6,6,6,6,6
B,3008,3008,3008,3008,3008,3008,3008
C,1931,1931,1931,1931,1931,1931,1931
D,1365,1365,1365,1365,1365,1365,1365
E,1190,1190,1190,1190,1190,1190,1190

In [20]:
df.groupby(by = 'Loan Grade')['Term','APR', 'Origination Fee', 'Loan Size', 'Outstanding Principal', 'Days Late', 'Delinquency Status'].size()

Loan Grade
A      2067
AA      433
AAA       6
B      3008
C      1931
D      1365
E      1190
dtype: int64

### Question 6

Display the count by <b>Loan Grade</b> of all the customers in the dataset. Also display the <b>max</b>, <b>min</b> and <b>mean</b> by <b>Loan Grade</b> of <b>Outstanding Principal</b>. Which loan grade has the least number of customers? Which loan grade has the lowest spread? Does the rating of the lowest spread customers conform to what you would expect if you were the lender?

In [26]:
df.groupby(by = 'Loan Grade').count()

,Term,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status
Loan Grade,,,,,,,
A,2067,2067,2067,2067,2067,2067,2067
AA,433,433,433,433,433,433,433
AAA,6,6,6,6,6,6,6
B,3008,3008,3008,3008,3008,3008,3008
C,1931,1931,1931,1931,1931,1931,1931
D,1365,1365,1365,1365,1365,1365,1365
E,1190,1190,1190,1190,1190,1190,1190

In [29]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].max()

Loan Grade
A      49351.47
AA     49332.70
AAA    21720.21
B      49380.34
C      50000.00
D      49436.30
E      50000.00
Name: Outstanding Principal, dtype: float64

In [30]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].min()

Loan Grade
A      0.0
AA     0.0
AAA    0.0
B      0.0
C      0.0
D      0.0
E      0.0
Name: Outstanding Principal, dtype: float64

In [31]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].mean()

Loan Grade
A      6428.668974
AA     6899.800139
AAA    9117.633333
B      7739.511007
C      7159.271932
D      6545.772066
E      7470.002361
Name: Outstanding Principal, dtype: float64

### Question 7

Does <b>Loan Size</b> provide any information about <b>Loan Grade</b>? Is a high risk borrower more likely to take bigger loans than a low risk borrower based on the data you have? Define in a few words what risk is to a lender? And to a borrower?

In [35]:
df.groupby(by = 'Loan Grade')['Loan Size'].mean()

Loan Grade
A      12282.244799
AA     13238.337182
AAA    12333.333333
B      12351.097074
C      11287.053340
D      12425.421245
E       9962.857143
Name: Loan Size, dtype: float64

In [36]:
df.groupby(by = 'Loan Grade')['Loan Size'].max()

Loan Grade
A      50000.0
AA     50000.0
AAA    25000.0
B      50000.0
C      50000.0
D      50000.0
E      50000.0
Name: Loan Size, dtype: float64

Based on the data, it does not appear that a high risk borrower is necessarily more likely to take bigger loans than a low risk borrower.

In [ ]:
Risk to a lender: That a borrower is unable to pay back a loan.

In [ ]:
Risk to a borrower: Affects what loans a borrower may be eligible for.

### Question 8

Display the count by <b>Loan Grade</b> of all the customers in the dataset and call that column <b>Count</b>. Also display the <b>max</b>, <b>min</b> and <b>mean</b> by <b>Loan Grade</b> of <b>Outstanding Principal</b> and call them <b>Max Balance</b>, <b>Min Balance</b> and <b>Average Balance</b>.

In [37]:
df.groupby(by = 'Loan Grade')['Loan Grade'].count()

Loan Grade
A      2067
AA      433
AAA       6
B      3008
C      1931
D      1365
E      1190
Name: Loan Grade, dtype: int64

In [44]:
df2 = df.copy()

In [48]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].max()

In [ ]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].min()

In [ ]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].mean()

In [ ]:
df.groupby(by = 'Loan Grade')['Outstanding Principal'].agg(['Max Balance','Min Balance','Average Balance'])

### Question 9

Write a code that takes the <b>Term</b> column and replace the values within that to <b>0</b> for <b>36</b> months and <b>1</b> for <b>60</b> months using a loop. Do the same using a lambda function. And then, using the <b>get_dummies</b> method (you might have to write additional code to drop redundant columns).

In [57]:
def dummy(column):
    if column == '60':
        return 1
    else:
        return 0

In [58]:
temp = df.copy()

In [59]:
temp.Term = temp.Term.apply(dummy)

In [60]:
temp.Term

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    0
9976    0
9977    0
9978    0
9979    0
9980    0
9981    0
9982    0
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    0
9992    0
9993    0
9994    0
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Term, Length: 10000, dtype: int64

In [62]:
temp = df.copy()

In [63]:
temp.Term.apply(lambda x: 0 if x == '36' else 1)

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
9970    1
9971    1
9972    1
9973    1
9974    1
9975    1
9976    1
9977    1
9978    1
9979    1
9980    1
9981    1
9982    1
9983    1
9984    1
9985    1
9986    1
9987    1
9988    1
9989    1
9990    1
9991    1
9992    1
9993    1
9994    1
9995    1
9996    1
9997    1
9998    1
9999    1
Name: Term, Length: 10000, dtype: int64

In [64]:
temp.Term = temp.Term.apply(lambda x: 0 if x == '36' else 1)

In [65]:
temp.Term

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
9970    1
9971    1
9972    1
9973    1
9974    1
9975    1
9976    1
9977    1
9978    1
9979    1
9980    1
9981    1
9982    1
9983    1
9984    1
9985    1
9986    1
9987    1
9988    1
9989    1
9990    1
9991    1
9992    1
9993    1
9994    1
9995    1
9996    1
9997    1
9998    1
9999    1
Name: Term, Length: 10000, dtype: int64

In [66]:
temp = df.copy()

In [67]:
pd.get_dummies(temp, columns=['Term'])

,Loan Grade,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status,Term_36,Term_60
0,C,16.94,492.00,8200.0,4733.79,89,Delinquent,1,0
1,B,18.64,1400.00,25000.0,22987.76,0,Current,0,1
2,C,20.44,325.00,6500.0,5296.60,0,Current,0,1
3,C,17.80,250.00,5000.0,0.00,0,Matured,1,0
4,B,13.43,239.10,5000.0,4388.82,0,Current,1,0
5,D,18.14,210.00,3500.0,3341.06,0,Current,1,0
6,B,12.62,150.00,3000.0,0.00,0,Matured,1,0
7,C,17.70,840.00,14000.0,6898.95,0,Current,1,0
8,B,15.78,672.00,12000.0,9678.61,0,Current,1,0
9,A,12.74,560.00,10000.0,9510.69,0,Current,1,0
10,A,12.09,280.00,5000.0,3466.24,0,Current,1,0
11,B,12.60,120.00,3000.0,1835.77,0,Current,1,0
12,E,27.21,450.00,7500.0,7368.22,15,In Grace,0,1
13,E,29.79,804.00,13400.0,13296.61,0,Current,0,1
14,B,14.21,168.00,3000.0,2712.37,0,Current,0,1
15,C,17.21,900.00,15000.0,14766.56,0,Current,0,1
16,A,10.38,500.00,10000.0,1485.01,0,Current,1,0
17,A,9.15,160.00,4000.0,2310.00,0,Current,1,0
18,D,29.58,540.00,9000.0,2931.28,0,Current,1,0
19,B,12.65,392.00,7000.0,0.00,0,Matured,1,0
20,A,11.61,1250.00,25000.0,0.00,0,Matured,1,0
21,E,29.79,124.76,3700.0,3642.04,0,Current,0,1
22,C,15.74,67.50,5400.0,3291.18,0,Current,1,0
23,AA,6.34,30.00,1500.0,901.98,0,Current,1,0
24,B,14.43,728.00,13000.0,11719.18,0,Current,1,0
25,A,12.07,672.00,12000.0,10706.11,0,Current,0,1
26,A,11.46,750.00,15000.0,3196.81,0,Current,1,0
27,B,14.48,314.70,10000.0,7718.66,0,Current,0,1
28,A,12.33,238.20,4000.0,4000.00,0,Current,1,0
29,A,13.35,996.80,17800.0,16411.63,0,Current,0,1
...,...,...,...,...,...,...,...,...,...
9970,E,29.81,335.43,4600.0,4600.00,0,Current,0,1
9971,B,13.73,140.00,3500.0,2053.31,0,Current,1,0
9972,A,10.88,560.00,10000.0,7424.87,0,Current,1,0
9973,B,14.94,550.00,11000.0,1630.62,0,Current,1,0
9974,B,14.16,952.00,17000.0,14346.15,0,Current,0,1
9975,C,16.84,177.04,2700.0,2700.00,0,Current,1,0
9976,E,29.23,60.00,1000.0,878.49,0,Current,1,0
9977,B,15.52,840.00,15000.0,14073.28,0,Current,0,1
9978,B,16.44,112.00,2000.0,1671.70,31,Delinquent,0,1
9979,D,22.29,510.00,8500.0,4494.41,79,Delinquent,1,0
9980,B,13.38,379.33,7000.0,6754.77,0,Current,1,0
9981,B,14.09,320.00,10000.0,7906.15,0,Current,0,1
9982,E,29.77,114.00,1900.0,1709.71,0,Current,1,0
9983,D,19.47,627.01,9300.0,9300.00,0,Current,0,1
9984,E,29.96,1212.00,20200.0,0.00,187,Charged Off,1,0
9985,A,11.11,220.00,5500.0,3362.34,0,Current,1,0
9986,A,11.68,550.00,11000.0,0.00,0,Matured,1,0
9987,A,10.93,476.00,8500.0,5731.12,0,Current,1,0
9988,C,16.23,402.83,7500.0,7500.00,0,Current,1,0
9989,C,16.03,360.00,6000.0,2741.13,0,Current,1,0
9990,B,13.02,1232.00,22000.0,19299.64,0,Current,1,0
9991,B,12.57,800.00,16000.0,0.00,0,Matured,1,0
9992,D,19.26,180.00,3000.0,0.00,0,Charged Off,1,0
9993,B,14.75,476.00,8500.0,8395.22,0,Current,0,1
9994,C,17.10,1014.00,16900.0,14104.14,0,Current,1,0
9995,A,9.88,436.13,15400.0,8980.34,0,Current,1,0
9996,B,14.51,800.00,16000.0,0.00,0,Matured,1,0
9997,B,12.80,1363.18,26000.0,24733.78,0,Current,1,0
9998,A,10.72,320.00,6400.0,0.00,0,Matured,1,0
9999,E,29.93,1685.00,33700.0,24462.63,51,Delinquent,1,0

In [68]:
temp = pd.get_dummies(temp, columns=['Term'])

In [69]:
temp

,Loan Grade,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status,Term_36,Term_60
0,C,16.94,492.00,8200.0,4733.79,89,Delinquent,1,0
1,B,18.64,1400.00,25000.0,22987.76,0,Current,0,1
2,C,20.44,325.00,6500.0,5296.60,0,Current,0,1
3,C,17.80,250.00,5000.0,0.00,0,Matured,1,0
4,B,13.43,239.10,5000.0,4388.82,0,Current,1,0
5,D,18.14,210.00,3500.0,3341.06,0,Current,1,0
6,B,12.62,150.00,3000.0,0.00,0,Matured,1,0
7,C,17.70,840.00,14000.0,6898.95,0,Current,1,0
8,B,15.78,672.00,12000.0,9678.61,0,Current,1,0
9,A,12.74,560.00,10000.0,9510.69,0,Current,1,0
10,A,12.09,280.00,5000.0,3466.24,0,Current,1,0
11,B,12.60,120.00,3000.0,1835.77,0,Current,1,0
12,E,27.21,450.00,7500.0,7368.22,15,In Grace,0,1
13,E,29.79,804.00,13400.0,13296.61,0,Current,0,1
14,B,14.21,168.00,3000.0,2712.37,0,Current,0,1
15,C,17.21,900.00,15000.0,14766.56,0,Current,0,1
16,A,10.38,500.00,10000.0,1485.01,0,Current,1,0
17,A,9.15,160.00,4000.0,2310.00,0,Current,1,0
18,D,29.58,540.00,9000.0,2931.28,0,Current,1,0
19,B,12.65,392.00,7000.0,0.00,0,Matured,1,0
20,A,11.61,1250.00,25000.0,0.00,0,Matured,1,0
21,E,29.79,124.76,3700.0,3642.04,0,Current,0,1
22,C,15.74,67.50,5400.0,3291.18,0,Current,1,0
23,AA,6.34,30.00,1500.0,901.98,0,Current,1,0
24,B,14.43,728.00,13000.0,11719.18,0,Current,1,0
25,A,12.07,672.00,12000.0,10706.11,0,Current,0,1
26,A,11.46,750.00,15000.0,3196.81,0,Current,1,0
27,B,14.48,314.70,10000.0,7718.66,0,Current,0,1
28,A,12.33,238.20,4000.0,4000.00,0,Current,1,0
29,A,13.35,996.80,17800.0,16411.63,0,Current,0,1
...,...,...,...,...,...,...,...,...,...
9970,E,29.81,335.43,4600.0,4600.00,0,Current,0,1
9971,B,13.73,140.00,3500.0,2053.31,0,Current,1,0
9972,A,10.88,560.00,10000.0,7424.87,0,Current,1,0
9973,B,14.94,550.00,11000.0,1630.62,0,Current,1,0
9974,B,14.16,952.00,17000.0,14346.15,0,Current,0,1
9975,C,16.84,177.04,2700.0,2700.00,0,Current,1,0
9976,E,29.23,60.00,1000.0,878.49,0,Current,1,0
9977,B,15.52,840.00,15000.0,14073.28,0,Current,0,1
9978,B,16.44,112.00,2000.0,1671.70,31,Delinquent,0,1
9979,D,22.29,510.00,8500.0,4494.41,79,Delinquent,1,0
9980,B,13.38,379.33,7000.0,6754.77,0,Current,1,0
9981,B,14.09,320.00,10000.0,7906.15,0,Current,0,1
9982,E,29.77,114.00,1900.0,1709.71,0,Current,1,0
9983,D,19.47,627.01,9300.0,9300.00,0,Current,0,1
9984,E,29.96,1212.00,20200.0,0.00,187,Charged Off,1,0
9985,A,11.11,220.00,5500.0,3362.34,0,Current,1,0
9986,A,11.68,550.00,11000.0,0.00,0,Matured,1,0
9987,A,10.93,476.00,8500.0,5731.12,0,Current,1,0
9988,C,16.23,402.83,7500.0,7500.00,0,Current,1,0
9989,C,16.03,360.00,6000.0,2741.13,0,Current,1,0
9990,B,13.02,1232.00,22000.0,19299.64,0,Current,1,0
9991,B,12.57,800.00,16000.0,0.00,0,Matured,1,0
9992,D,19.26,180.00,3000.0,0.00,0,Charged Off,1,0
9993,B,14.75,476.00,8500.0,8395.22,0,Current,0,1
9994,C,17.10,1014.00,16900.0,14104.14,0,Current,1,0
9995,A,9.88,436.13,15400.0,8980.34,0,Current,1,0
9996,B,14.51,800.00,16000.0,0.00,0,Matured,1,0
9997,B,12.80,1363.18,26000.0,24733.78,0,Current,1,0
9998,A,10.72,320.00,6400.0,0.00,0,Matured,1,0
9999,E,29.93,1685.00,33700.0,24462.63,51,Delinquent,1,0

In [70]:
temp.drop(['Term_60'], axis = 1, inplace = True)

In [71]:
temp

,Loan Grade,APR,Origination Fee,Loan Size,Outstanding Principal,Days Late,Delinquency Status,Term_36
0,C,16.94,492.00,8200.0,4733.79,89,Delinquent,1
1,B,18.64,1400.00,25000.0,22987.76,0,Current,0
2,C,20.44,325.00,6500.0,5296.60,0,Current,0
3,C,17.80,250.00,5000.0,0.00,0,Matured,1
4,B,13.43,239.10,5000.0,4388.82,0,Current,1
5,D,18.14,210.00,3500.0,3341.06,0,Current,1
6,B,12.62,150.00,3000.0,0.00,0,Matured,1
7,C,17.70,840.00,14000.0,6898.95,0,Current,1
8,B,15.78,672.00,12000.0,9678.61,0,Current,1
9,A,12.74,560.00,10000.0,9510.69,0,Current,1
10,A,12.09,280.00,5000.0,3466.24,0,Current,1
11,B,12.60,120.00,3000.0,1835.77,0,Current,1
12,E,27.21,450.00,7500.0,7368.22,15,In Grace,0
13,E,29.79,804.00,13400.0,13296.61,0,Current,0
14,B,14.21,168.00,3000.0,2712.37,0,Current,0
15,C,17.21,900.00,15000.0,14766.56,0,Current,0
16,A,10.38,500.00,10000.0,1485.01,0,Current,1
17,A,9.15,160.00,4000.0,2310.00,0,Current,1
18,D,29.58,540.00,9000.0,2931.28,0,Current,1
19,B,12.65,392.00,7000.0,0.00,0,Matured,1
20,A,11.61,1250.00,25000.0,0.00,0,Matured,1
21,E,29.79,124.76,3700.0,3642.04,0,Current,0
22,C,15.74,67.50,5400.0,3291.18,0,Current,1
23,AA,6.34,30.00,1500.0,901.98,0,Current,1
24,B,14.43,728.00,13000.0,11719.18,0,Current,1
25,A,12.07,672.00,12000.0,10706.11,0,Current,0
26,A,11.46,750.00,15000.0,3196.81,0,Current,1
27,B,14.48,314.70,10000.0,7718.66,0,Current,0
28,A,12.33,238.20,4000.0,4000.00,0,Current,1
29,A,13.35,996.80,17800.0,16411.63,0,Current,0
...,...,...,...,...,...,...,...,...
9970,E,29.81,335.43,4600.0,4600.00,0,Current,0
9971,B,13.73,140.00,3500.0,2053.31,0,Current,1
9972,A,10.88,560.00,10000.0,7424.87,0,Current,1
9973,B,14.94,550.00,11000.0,1630.62,0,Current,1
9974,B,14.16,952.00,17000.0,14346.15,0,Current,0
9975,C,16.84,177.04,2700.0,2700.00,0,Current,1
9976,E,29.23,60.00,1000.0,878.49,0,Current,1
9977,B,15.52,840.00,15000.0,14073.28,0,Current,0
9978,B,16.44,112.00,2000.0,1671.70,31,Delinquent,0
9979,D,22.29,510.00,8500.0,4494.41,79,Delinquent,1
9980,B,13.38,379.33,7000.0,6754.77,0,Current,1
9981,B,14.09,320.00,10000.0,7906.15,0,Current,0
9982,E,29.77,114.00,1900.0,1709.71,0,Current,1
9983,D,19.47,627.01,9300.0,9300.00,0,Current,0
9984,E,29.96,1212.00,20200.0,0.00,187,Charged Off,1
9985,A,11.11,220.00,5500.0,3362.34,0,Current,1
9986,A,11.68,550.00,11000.0,0.00,0,Matured,1
9987,A,10.93,476.00,8500.0,5731.12,0,Current,1
9988,C,16.23,402.83,7500.0,7500.00,0,Current,1
9989,C,16.03,360.00,6000.0,2741.13,0,Current,1
9990,B,13.02,1232.00,22000.0,19299.64,0,Current,1
9991,B,12.57,800.00,16000.0,0.00,0,Matured,1
9992,D,19.26,180.00,3000.0,0.00,0,Charged Off,1
9993,B,14.75,476.00,8500.0,8395.22,0,Current,0
9994,C,17.10,1014.00,16900.0,14104.14,0,Current,1
9995,A,9.88,436.13,15400.0,8980.34,0,Current,1
9996,B,14.51,800.00,16000.0,0.00,0,Matured,1
9997,B,12.80,1363.18,26000.0,24733.78,0,Current,1
9998,A,10.72,320.00,6400.0,0.00,0,Matured,1
9999,E,29.93,1685.00,33700.0,24462.63,51,Delinquent,1

### Question 10

<p>Ask an interesting question of this data set and provide a solution to answer that.</p>
<p>The goal is to help teach your fellow students all possible questions we can collectively ask of this dataset. Your question should be as clear as possible and as short as possible. Try to avoid asking questions that are too trivial or obvious.</p>

<p>This is a bonus point question. The only way not to get full points are if you do the following:
<ul>
<li>You do not perform this task.
<li>You do not include a solution. 
</ul>
</p>
<p>If the solution you provide is incorrect, you will still receive full points. But you must make an honest effort to get it right.
</p>

Write your question here: On average, do those with Loan Grade AA who have Delinquent Status have a larger Loan Size than those Loan Grade AA folks who have Charged Off Status?

In [ ]:
Write your solution here.

In [54]:
df.groupby(by=['Loan Grade','Delinquency Status']).mean()

                                       Term        APR  Origination Fee  \
Loan Grade Delinquency Status
A          Charged Off            36.000000  10.933488       802.944186
           Current                41.445255  11.337506       596.004130
           Delinquent             37.263158  11.323158       591.768421
           In Grace               37.600000  10.724667       689.726000
           Matured                36.767442  10.747500       636.290988
           Partially Charged Off  36.000000  11.505000      1000.000000
AA         Charged Off            36.000000   7.946667       318.000000
           Current                48.222222   8.683086       396.531914
           Delinquent             48.000000   8.225000       505.000000
           In Grace               36.000000   7.770000       285.000000
           Matured                37.176471   7.798627       404.344314
           Partially Charged Off  36.000000   8.490000       390.000000
AAA        Current                50.400000   6.592000       138.000000
           Matured                36.000000   6.150000        50.000000
B          Charged Off            38.823529  14.048941       611.552706
           Current                44.313464  14.453702       636.626003
           Delinquent             42.400000  14.661667       596.219000
           In Grace               40.645161  14.203548       487.482258
           Matured                38.685315  14.018904       641.435734
           Partially Charged Off  42.000000  13.750000       627.500000
C          Charged Off            36.564706  17.139882       683.096706
           Current                40.216852  17.273965       620.344546
           Delinquent             37.745455  17.724545       648.588727
           In Grace               38.285714  17.335238       704.308095
           Matured                36.405063  17.508312       722.990759
           Partially Charged Off  36.000000  19.180000       480.000000
D          Charged Off            36.167832  23.315874       768.015385
           Current                43.697105  20.664165       695.133641
           Delinquent             36.545455  22.048864       752.769545
           In Grace               38.769231  22.016538       793.734615
           Matured                36.761905  22.783889       733.759802
           Partially Charged Off  36.000000  23.310000       510.000000
E          Charged Off            36.000000  28.705417       625.765000
           Current                51.353879  26.971392       589.272954
           Delinquent             41.189189  28.619730       522.822703
           In Grace               43.058824  28.094706       647.117647
           Matured                38.578512  28.941736       580.107934
           Partially Charged Off  36.000000  29.890000       468.000000

                                     Loan Size  Outstanding Principal  \
Loan Grade Delinquency Status
A          Charged Off            16411.627907               0.000000
           Current                11880.900243            7933.469100
           Delinquent             11921.052632            5874.449474
           In Grace               15106.666667            8108.860667
           Matured                13536.046512               0.000000
           Partially Charged Off  20000.000000            6094.060000
AA         Charged Off            10600.000000               0.000000
           Current                12816.049383            9120.565494
           Delinquent             17500.000000           12054.355000
           In Grace                9500.000000            4436.580000
           Matured                14612.745098               0.000000
           Partially Charged Off  13000.000000            4004.950000
AAA        Current                13800.000000           10941.160000
           Matured                 5000.000000               0.000000
B          Charged Off            12580.000000               0.000000
           Current                12219.383076            9386.062430
           Delinquent             12220.000000            8915.687167
           In Grace                9870.967742            6779.258710
           Matured                13234.265734               0.000000
           Partially Charged Off  12950.000000            4546.772500
C          Charged Off            12488.235294               0.000000
           Current                10986.479425            8595.427270
           Delinquent             11474.545455            8889.667818
           In Grace               12038.095238            8218.104286
           Matured                12715.611814               0.000000
           Partially Charged Off   8000.000000            1721.515000
D          Charged Off            13203.496503               0.000000
           Current                11985.189310            9240.566704
           Delinquent             13443.181818            8758.232045
           In Grace               14453.846154            9389.400385
           Matured                13189.682540               0.000000
           Partially Charged Off   9400.000000            3731.675000
E          Charged Off            11063.888889               0.000000
           Current                 9855.472901            8980.123103
           Delinquent              9005.405405            7494.603243
           In Grace               11541.176471            9443.448235
           Matured                10249.586777               0.000000
           Partially Charged Off   7800.000000             584.015000

                                   Days Late
Loan Grade Delinquency Status
A          Charged Off            270.511628
           Current                  0.000000
           Delinquent              52.052632
           In Grace                 7.666667
           Matured                  0.000000
           Partially Charged Off    0.000000
AA         Charged Off            336.000000
           Current                  0.000000
           Delinquent              67.000000
           In Grace                13.000000
           Matured                  0.000000
           Partially Charged Off   43.000000
AAA        Current                  0.000000
           Matured                  0.000000
B          Charged Off            316.976471
           Current                  0.000000
           Delinquent              52.566667
           In Grace                 8.225806
           Matured                  0.000000
           Partially Charged Off    6.000000
C          Charged Off            309.870588
           Current                  0.000000
           Delinquent              50.236364
           In Grace                 8.857143
           Matured                  0.000000
           Partially Charged Off    0.000000
D          Charged Off            355.272727
           Current                  0.000000
           Delinquent              60.204545
           In Grace                 8.807692
           Matured                  0.000000
           Partially Charged Off    0.000000
E          Charged Off            269.222222
           Current                  0.000000
           Delinquent              55.135135
           In Grace                 7.588235
           Matured                  0.000000
           Partially Charged Off    0.000000

In [ ]:
Based off the data, Loan Grade AA individuals with Charged Off Status have, on average, a larger Loan Size than Loan Grade AA indiviuals with Delinquent Status.